/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as PaymentIdRouteImport } from './routes/payment.$id'
import { Route as DashboardTestingRouteImport } from './routes/dashboard.testing'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPendingRouteImport } from './routes/dashboard.pending'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardOfflineRouteImport } from './routes/dashboard.offline'
import { Route as DashboardNewRouteImport } from './routes/dashboard.new'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard.agents'
import { Route as AgentSyncRouteImport } from './routes/agent.sync'
import { Route as AgentScanRouteImport } from './routes/agent.scan'
import { Route as AgentProfileRouteImport } from './routes/agent.profile'
import { Route as AgentDeliveriesRouteImport } from './routes/agent.deliveries'
import { Route as AgentCertificateRouteImport } from './routes/agent.certificate'
import { Route as DashboardProofsIndexRouteImport } from './routes/dashboard.proofs.index'
import { Route as DashboardProofsIdRouteImport } from './routes/dashboard.proofs.$id'
import { Route as DashboardCertificateIdRouteImport } from './routes/dashboard.certificate.$id'
import { Route as AgentDeliveryIdRouteImport } from './routes/agent.delivery.$id'

const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const PaymentIdRoute = PaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTestingRoute = DashboardTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPendingRoute = DashboardPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOfflineRoute = DashboardOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const AgentSyncRoute = AgentSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AgentRoute,
} as any)
const AgentScanRoute = AgentScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AgentRoute,
} as any)
const AgentProfileRoute = AgentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AgentRoute,
} as any)
const AgentDeliveriesRoute = AgentDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AgentRoute,
} as any)
const AgentCertificateRoute = AgentCertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => AgentRoute,
} as any)
const DashboardProofsIndexRoute = DashboardProofsIndexRouteImport.update({
  id: '/proofs/',
  path: '/proofs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProofsIdRoute = DashboardProofsIdRouteImport.update({
  id: '/proofs/$id',
  path: '/proofs/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificateIdRoute = DashboardCertificateIdRouteImport.update({
  id: '/certificate/$id',
  path: '/certificate/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const AgentDeliveryIdRoute = AgentDeliveryIdRouteImport.update({
  id: '/delivery/$id',
  path: '/delivery/$id',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/agent/certificate': typeof AgentCertificateRoute
  '/agent/deliveries': typeof AgentDeliveriesRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/scan': typeof AgentScanRoute
  '/agent/sync': typeof AgentSyncRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/offline': typeof DashboardOfflineRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/pending': typeof DashboardPendingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/testing': typeof DashboardTestingRoute
  '/payment/$id': typeof PaymentIdRoute
  '/agent/': typeof AgentIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/agent/delivery/$id': typeof AgentDeliveryIdRoute
  '/dashboard/certificate/$id': typeof DashboardCertificateIdRoute
  '/dashboard/proofs/$id': typeof DashboardProofsIdRoute
  '/dashboard/proofs/': typeof DashboardProofsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/agent/certificate': typeof AgentCertificateRoute
  '/agent/deliveries': typeof AgentDeliveriesRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/scan': typeof AgentScanRoute
  '/agent/sync': typeof AgentSyncRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/offline': typeof DashboardOfflineRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/pending': typeof DashboardPendingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/testing': typeof DashboardTestingRoute
  '/payment/$id': typeof PaymentIdRoute
  '/agent': typeof AgentIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/agent/delivery/$id': typeof AgentDeliveryIdRoute
  '/dashboard/certificate/$id': typeof DashboardCertificateIdRoute
  '/dashboard/proofs/$id': typeof DashboardProofsIdRoute
  '/dashboard/proofs': typeof DashboardProofsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/agent/certificate': typeof AgentCertificateRoute
  '/agent/deliveries': typeof AgentDeliveriesRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/scan': typeof AgentScanRoute
  '/agent/sync': typeof AgentSyncRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/offline': typeof DashboardOfflineRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/pending': typeof DashboardPendingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/testing': typeof DashboardTestingRoute
  '/payment/$id': typeof PaymentIdRoute
  '/agent/': typeof AgentIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/agent/delivery/$id': typeof AgentDeliveryIdRoute
  '/dashboard/certificate/$id': typeof DashboardCertificateIdRoute
  '/dashboard/proofs/$id': typeof DashboardProofsIdRoute
  '/dashboard/proofs/': typeof DashboardProofsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/agent/certificate'
    | '/agent/deliveries'
    | '/agent/profile'
    | '/agent/scan'
    | '/agent/sync'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/history'
    | '/dashboard/new'
    | '/dashboard/offline'
    | '/dashboard/payments'
    | '/dashboard/pending'
    | '/dashboard/settings'
    | '/dashboard/testing'
    | '/payment/$id'
    | '/agent/'
    | '/dashboard/'
    | '/agent/delivery/$id'
    | '/dashboard/certificate/$id'
    | '/dashboard/proofs/$id'
    | '/dashboard/proofs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/agent/certificate'
    | '/agent/deliveries'
    | '/agent/profile'
    | '/agent/scan'
    | '/agent/sync'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/history'
    | '/dashboard/new'
    | '/dashboard/offline'
    | '/dashboard/payments'
    | '/dashboard/pending'
    | '/dashboard/settings'
    | '/dashboard/testing'
    | '/payment/$id'
    | '/agent'
    | '/dashboard'
    | '/agent/delivery/$id'
    | '/dashboard/certificate/$id'
    | '/dashboard/proofs/$id'
    | '/dashboard/proofs'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/agent/certificate'
    | '/agent/deliveries'
    | '/agent/profile'
    | '/agent/scan'
    | '/agent/sync'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/history'
    | '/dashboard/new'
    | '/dashboard/offline'
    | '/dashboard/payments'
    | '/dashboard/pending'
    | '/dashboard/settings'
    | '/dashboard/testing'
    | '/payment/$id'
    | '/agent/'
    | '/dashboard/'
    | '/agent/delivery/$id'
    | '/dashboard/certificate/$id'
    | '/dashboard/proofs/$id'
    | '/dashboard/proofs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  PaymentIdRoute: typeof PaymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/payment/$id': {
      id: '/payment/$id'
      path: '/payment/$id'
      fullPath: '/payment/$id'
      preLoaderRoute: typeof PaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/testing': {
      id: '/dashboard/testing'
      path: '/testing'
      fullPath: '/dashboard/testing'
      preLoaderRoute: typeof DashboardTestingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pending': {
      id: '/dashboard/pending'
      path: '/pending'
      fullPath: '/dashboard/pending'
      preLoaderRoute: typeof DashboardPendingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/offline': {
      id: '/dashboard/offline'
      path: '/offline'
      fullPath: '/dashboard/offline'
      preLoaderRoute: typeof DashboardOfflineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/agent/sync': {
      id: '/agent/sync'
      path: '/sync'
      fullPath: '/agent/sync'
      preLoaderRoute: typeof AgentSyncRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/scan': {
      id: '/agent/scan'
      path: '/scan'
      fullPath: '/agent/scan'
      preLoaderRoute: typeof AgentScanRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/profile': {
      id: '/agent/profile'
      path: '/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentProfileRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/deliveries': {
      id: '/agent/deliveries'
      path: '/deliveries'
      fullPath: '/agent/deliveries'
      preLoaderRoute: typeof AgentDeliveriesRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/certificate': {
      id: '/agent/certificate'
      path: '/certificate'
      fullPath: '/agent/certificate'
      preLoaderRoute: typeof AgentCertificateRouteImport
      parentRoute: typeof AgentRoute
    }
    '/dashboard/proofs/': {
      id: '/dashboard/proofs/'
      path: '/proofs'
      fullPath: '/dashboard/proofs/'
      preLoaderRoute: typeof DashboardProofsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/proofs/$id': {
      id: '/dashboard/proofs/$id'
      path: '/proofs/$id'
      fullPath: '/dashboard/proofs/$id'
      preLoaderRoute: typeof DashboardProofsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificate/$id': {
      id: '/dashboard/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/dashboard/certificate/$id'
      preLoaderRoute: typeof DashboardCertificateIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/agent/delivery/$id': {
      id: '/agent/delivery/$id'
      path: '/delivery/$id'
      fullPath: '/agent/delivery/$id'
      preLoaderRoute: typeof AgentDeliveryIdRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface AgentRouteChildren {
  AgentCertificateRoute: typeof AgentCertificateRoute
  AgentDeliveriesRoute: typeof AgentDeliveriesRoute
  AgentProfileRoute: typeof AgentProfileRoute
  AgentScanRoute: typeof AgentScanRoute
  AgentSyncRoute: typeof AgentSyncRoute
  AgentIndexRoute: typeof AgentIndexRoute
  AgentDeliveryIdRoute: typeof AgentDeliveryIdRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentCertificateRoute: AgentCertificateRoute,
  AgentDeliveriesRoute: AgentDeliveriesRoute,
  AgentProfileRoute: AgentProfileRoute,
  AgentScanRoute: AgentScanRoute,
  AgentSyncRoute: AgentSyncRoute,
  AgentIndexRoute: AgentIndexRoute,
  AgentDeliveryIdRoute: AgentDeliveryIdRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface DashboardRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardOfflineRoute: typeof DashboardOfflineRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardPendingRoute: typeof DashboardPendingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTestingRoute: typeof DashboardTestingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCertificateIdRoute: typeof DashboardCertificateIdRoute
  DashboardProofsIdRoute: typeof DashboardProofsIdRoute
  DashboardProofsIndexRoute: typeof DashboardProofsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardNewRoute: DashboardNewRoute,
  DashboardOfflineRoute: DashboardOfflineRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardPendingRoute: DashboardPendingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTestingRoute: DashboardTestingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCertificateIdRoute: DashboardCertificateIdRoute,
  DashboardProofsIdRoute: DashboardProofsIdRoute,
  DashboardProofsIndexRoute: DashboardProofsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  PaymentIdRoute: PaymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
